---
name: Basic2Component Environment US
schema_version: "1.0"
description: Environment All-In-One example to deploy a two component stack, no api-key in us-east
resource_group: Default
tags:
  - environment:basic2comp-env-us
type: ENVIRONMENT
location: "us-east"
blueprint:
  git_repo_url: https://github.ibm.com/steve-strutt/environment-aio-basic2comp-us
  git_token: ""
  sha_value: ""
  git_repo_folder: "basic2comp-blueprint.yaml"
  git_release: ""
  git_branch: master
  version: ""
config:
  - git_repo_url: https://github.ibm.com/steve-strutt/environment-aio-basic2comp-us
    git_token: ""
    sha_value: ""
    git_repo_folder: "basic2comp-config-us.yaml"
    git_release: ""
    git_branch: master
    version: ""
settings: []
